title: Animated signs
hero_image: images/banner.png
description: Create an animated "Reduce, Reuse, Recycle" sign on the SenseHAT
version: 4
listed: false
copyedit: false
last_tested: "2020-02-18"
steps:
  - title: Introduction
  - title: Animated signs
